### ISSUE TITLE
[1.18.2][Feature request] Blue Skies backport and Undergarden compat.

### ISSUE THREAD

**Issue by V972** [ultrakoxxd/idontwantportalyet#3]
What is says in the title. 
I plan to use this mod in a modpack to gate dimentions, but I have to be on 1.18.2 and Blue Skies compat was only added for 1.19 according to changelog as well we would be nice to have Undergarden support.

Pretty please ;)

**Comment by ultrakoxxd** [comment]
no problem give me arround 20h

**Comment by ultrakoxxd** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/i-dont-want-portal-yet/files/4771718

**Comment by V972** [comment]
Just tested, both mods work, but unfortunately, Undergarden portal doesn't get destroyed on disabling like Blue Skies' ones do.
Actually, Nether portal isn't getting destroyed as well.

...also, also, don't know if I should make it a separate issue or if I add here, but seems like End Remastered's eyes are still placable in end frames even with end disabled (vanilla ones are not so they work at least) so....if it's okay, End Remastered support maybe please? 👉👈

Still, thank you very much already!

**Comment by ultrakoxxd** [comment]
It doesn't break because its coded different way its more optimized but i thought about making all portals break, about end remastered i will look into it
